[package]
name = "fedihub-registry"
version = "0.0.0"
authors = ["Alex Kotov <kotovalexarian@gmail.com>"]
edition = "2018"
description = "User registry"
readme = "README.md"
homepage = "https://fedihub.com"
repository = "https://github.com/fedihubcom/registry"
license = "MIT"
license-file = "LICENSE"
keywords = ["web"]
categories = []
publish = true

[dependencies]
