[package]
name = "fedihub-registry"
version = "0.0.0"
authors = ["Alex Kotov <kotovalexarian@gmail.com>"]
edition = "2018"
description = "User registry"
readme = "README.md"
homepage = "https://fedihub.com"
repository = "https://github.com/fedihubcom/registry"
license-file = "LICENSE"
keywords = ["web"]
categories = []
publish = true

[dependencies]
rocket = "0.4.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["handlebars_templates", "tera_templates"]
