#!/usr/bin/env ruby
# frozen_string_literal: true

Warning[:deprecated] = false

require 'bundler/setup'

lib = File.expand_path('../lib', __dir__).freeze
$LOAD_PATH.unshift lib unless $LOAD_PATH.include? lib

exec 'rackup'
