[package]
name = "rocket_csrf"
version = "0.0.0"
authors = ["Alex Kotov <kotovalexarian@gmail.com>"]
edition = "2018"

[dependencies]
base64 = { version = "^0.13.0" }
rand   = { version = "^0.7.3" }
rocket = { version = "^0.4.5", features = ["private-cookies"] }
